/**
 * Simplified Chinese translation for bootstrap-datetimepicker
 * Yuan Cheung <advanimal@gmail.com>
 */
;(function($){
	$.fn.datetimepicker.dates['zh-CN'] = {
		      days: [$l('type.hand.commom.date.days.sunday'),
		             $l('type.hand.commom.date.days.monday'),
		             $l('type.hand.commom.date.days.tuesday'),
		             $l('type.hand.commom.date.days.wednesday'),
		             $l('type.hand.commom.date.days.thursday'),
		             $l('type.hand.commom.date.days.friday'),
		             $l('type.hand.commom.date.days.saturday'),
		             $l('type.hand.commom.date.days.sunday')],
		      daysShort: [$l('type.hand.commom.date.daysshort.sunday'),
		                  $l('type.hand.commom.date.daysshort.monday'),
		                  $l('type.hand.commom.date.daysshort.tuesday'),
		                  $l('type.hand.commom.date.daysshort.wednesday'),
		                  $l('type.hand.commom.date.daysshort.thursday'),
		                  $l('type.hand.commom.date.daysshort.friday'),
		                  $l('type.hand.commom.date.daysshort.saturday'),
		                  $l('type.hand.commom.date.daysshort.sunday')],
		      daysMin:  [$l('type.hand.commom.date.daysmin.sunday'),
		                 $l('type.hand.commom.date.daysmin.monday'),
		                 $l('type.hand.commom.date.daysmin.tuesday'),
		                 $l('type.hand.commom.date.daysmin.wednesday'),
		                 $l('type.hand.commom.date.daysmin.thursday'),
		                 $l('type.hand.commom.date.daysmin.friday'),
		                 $l('type.hand.commom.date.daysmin.saturday'),
		                 $l('type.hand.commom.date.daysmin.sunday')],
		      months: [$l('type.hand.commom.date.months.january'),
		               $l('type.hand.commom.date.months.february'),
		               $l('type.hand.commom.date.months.march'),
		               $l('type.hand.commom.date.months.april'),
		               $l('type.hand.commom.date.months.may'),
		               $l('type.hand.commom.date.months.june'),
		               $l('type.hand.commom.date.months.july'),
		               $l('type.hand.commom.date.months.august'),
		               $l('type.hand.commom.date.months.september'),
		               $l('type.hand.commom.date.months.october'),
		               $l('type.hand.commom.date.months.november'),
		               $l('type.hand.commom.date.months.december')],
		      monthsShort: [$l('type.hand.commom.date.monthsshort.january'),
		                    $l('type.hand.commom.date.monthsshort.february'),
		                    $l('type.hand.commom.date.monthsshort.march'),
		                    $l('type.hand.commom.date.monthsshort.april'),
		                    $l('type.hand.commom.date.monthsshort.may'),
		                    $l('type.hand.commom.date.monthsshort.june'),
		                    $l('type.hand.commom.date.monthsshort.july'),
		                    $l('type.hand.commom.date.monthsshort.august'),
		                    $l('type.hand.commom.date.monthsshort.september'),
		                    $l('type.hand.commom.date.monthsshort.october'),
		                    $l('type.hand.commom.date.monthsshort.november'),
		                    $l('type.hand.commom.date.monthsshort.december')],
		      today:  $l("type.hand.commom.date.today"),
		      suffix: [],
		      meridiem: [$l('type.hand.commom.date.meridiem.am'),
		                 $l('type.hand.commom.date.meridiem.pm')]
		  };
}(jQuery));
